import java.util.Scanner;
public class Ex3 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Scanner scn = new Scanner(System.in);
		System.out.print("請輸入身份證字號開頭英文(大寫)");
		char PP = scn.next().charAt(0);
		switch(PP){
		case'A':
		System.out.print(PP+"為台北市10");
		break;
		case'B':
			System.out.print(PP+"為台中市11");
			break;
		case'C':
			System.out.print(PP+"為基隆市12");
			break;
		case'D':
			System.out.print(PP+"為台南市13");
			break;
		case'E':
			System.out.print(PP+"為高雄市14");
			break;
		case'F':
			System.out.print(PP+"為台北縣15");
			break;
		case'G':
			System.out.print(PP+"為宜蘭縣16");
			break;
		case'H':
			System.out.print(PP+"為桃園縣17");
			break;
		case'I':
			System.out.print(PP+"為嘉義市34");
			break;
		case'J':
			System.out.print(PP+"為新竹縣18");
			break;
		case'K':
			System.out.print(PP+"為苗栗縣19");
			break;
		case'L':
			System.out.print(PP+"為台中縣20");
			break;
		case'M':
			System.out.print(PP+"為南投縣21");
			break;
		case'N':
			System.out.print(PP+"為彰化縣22");
			break;
		case'O':
			System.out.print(PP+"為新竹市35");
			break;
		case'P':
			System.out.print(PP+"為雲林縣23");
			break;
		case'Q':
			System.out.print(PP+"為嘉義縣24");
			break;
		case'R':
			System.out.print(PP+"為台南市25");
			break;
		case'S':
			System.out.print(PP+"為高雄縣26");
			break;
		case'T':
			System.out.print(PP+"為屏東縣27");
			break;
		case'U':
			System.out.print(PP+"為花蓮縣28");
			break;
		case'V':
			System.out.print(PP+"為台東縣29");
			break;
		case'X':
			System.out.print(PP+"為澎湖縣30");
			break;
		case'Y':
			System.out.print(PP+"為陽明山31");
			break;
		case'W':
			System.out.print(PP+"為金門32");
			break;
		case'Z':
			System.out.print(PP+"為馬祖33");
			break;
		default:
			System.out.print("沒有這個地區!");
			break;
	}
	}
}
